<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/organization.proto

namespace Toit\Model\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.User.State</code>
 */
class State extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp cli_installed_at = 1;</code>
     */
    protected $cli_installed_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp vscode_ext_installed_at = 2;</code>
     */
    protected $vscode_ext_installed_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $cli_installed_at
     *     @type \Google\Protobuf\Timestamp $vscode_ext_installed_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp cli_installed_at = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCliInstalledAt()
    {
        return $this->cli_installed_at;
    }

    public function hasCliInstalledAt()
    {
        return isset($this->cli_installed_at);
    }

    public function clearCliInstalledAt()
    {
        unset($this->cli_installed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp cli_installed_at = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCliInstalledAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->cli_installed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp vscode_ext_installed_at = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getVscodeExtInstalledAt()
    {
        return $this->vscode_ext_installed_at;
    }

    public function hasVscodeExtInstalledAt()
    {
        return isset($this->vscode_ext_installed_at);
    }

    public function clearVscodeExtInstalledAt()
    {
        unset($this->vscode_ext_installed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp vscode_ext_installed_at = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setVscodeExtInstalledAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->vscode_ext_installed_at = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Toit\Model\User_State::class);

