<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/app.proto

namespace Toit\Model\JobSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.JobSpec.PubSub</code>
 */
class PubSub extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .toit.model.pubsub.Topic subscriptions = 1;</code>
     */
    private $subscriptions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\Pubsub\Topic[]|\Google\Protobuf\Internal\RepeatedField $subscriptions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\App::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.pubsub.Topic subscriptions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.pubsub.Topic subscriptions = 1;</code>
     * @param \Toit\Model\Pubsub\Topic[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubscriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\Pubsub\Topic::class);
        $this->subscriptions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PubSub::class, \Toit\Model\JobSpec_PubSub::class);

