<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/app.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.App</code>
 */
class App extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes app_id = 1;</code>
     */
    protected $app_id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string namespace = 3;</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     */
    protected $revision = 0;
    /**
     * Generated from protobuf field <code>bytes source_id = 5;</code>
     */
    protected $source_id = '';
    /**
     * Generated from protobuf field <code>map<string, .toit.model.JobSpec> jobs = 6;</code>
     */
    private $jobs;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>bytes created_by = 8;</code>
     */
    protected $created_by = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_id
     *     @type string $name
     *     @type string $namespace
     *     @type int|string $revision
     *     @type string $source_id
     *     @type array|\Google\Protobuf\Internal\MapField $jobs
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type string $created_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\App::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes app_id = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>bytes app_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, False);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 3;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes source_id = 5;</code>
     * @return string
     */
    public function getSourceId()
    {
        return $this->source_id;
    }

    /**
     * Generated from protobuf field <code>bytes source_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->source_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .toit.model.JobSpec> jobs = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getJobs()
    {
        return $this->jobs;
    }

    /**
     * Generated from protobuf field <code>map<string, .toit.model.JobSpec> jobs = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setJobs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\JobSpec::class);
        $this->jobs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes created_by = 8;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>bytes created_by = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, False);
        $this->created_by = $var;

        return $this;
    }

}

