<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/program.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.CompilationResult</code>
 */
class CompilationResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string error = 1;</code>
     */
    protected $error = '';
    /**
     * Generated from protobuf field <code>bytes snapshot_out = 2;</code>
     */
    protected $snapshot_out = '';
    /**
     * Generated from protobuf field <code>bytes snapshot_err = 3;</code>
     */
    protected $snapshot_err = '';
    /**
     * Generated from protobuf field <code>int32 snapshot_exitcode = 4;</code>
     */
    protected $snapshot_exitcode = 0;
    /**
     * Generated from protobuf field <code>bytes image_out = 5;</code>
     */
    protected $image_out = '';
    /**
     * Generated from protobuf field <code>bytes image_err = 6;</code>
     */
    protected $image_err = '';
    /**
     * Generated from protobuf field <code>int32 image_exitcode = 7;</code>
     */
    protected $image_exitcode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error
     *     @type string $snapshot_out
     *     @type string $snapshot_err
     *     @type int $snapshot_exitcode
     *     @type string $image_out
     *     @type string $image_err
     *     @type int $image_exitcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string error = 1;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_out = 2;</code>
     * @return string
     */
    public function getSnapshotOut()
    {
        return $this->snapshot_out;
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_out = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSnapshotOut($var)
    {
        GPBUtil::checkString($var, False);
        $this->snapshot_out = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_err = 3;</code>
     * @return string
     */
    public function getSnapshotErr()
    {
        return $this->snapshot_err;
    }

    /**
     * Generated from protobuf field <code>bytes snapshot_err = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSnapshotErr($var)
    {
        GPBUtil::checkString($var, False);
        $this->snapshot_err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 snapshot_exitcode = 4;</code>
     * @return int
     */
    public function getSnapshotExitcode()
    {
        return $this->snapshot_exitcode;
    }

    /**
     * Generated from protobuf field <code>int32 snapshot_exitcode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSnapshotExitcode($var)
    {
        GPBUtil::checkInt32($var);
        $this->snapshot_exitcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes image_out = 5;</code>
     * @return string
     */
    public function getImageOut()
    {
        return $this->image_out;
    }

    /**
     * Generated from protobuf field <code>bytes image_out = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setImageOut($var)
    {
        GPBUtil::checkString($var, False);
        $this->image_out = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes image_err = 6;</code>
     * @return string
     */
    public function getImageErr()
    {
        return $this->image_err;
    }

    /**
     * Generated from protobuf field <code>bytes image_err = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setImageErr($var)
    {
        GPBUtil::checkString($var, False);
        $this->image_err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 image_exitcode = 7;</code>
     * @return int
     */
    public function getImageExitcode()
    {
        return $this->image_exitcode;
    }

    /**
     * Generated from protobuf field <code>int32 image_exitcode = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setImageExitcode($var)
    {
        GPBUtil::checkInt32($var);
        $this->image_exitcode = $var;

        return $this;
    }

}

