<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/program.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.Compilation</code>
 */
class Compilation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string sdk = 2;</code>
     */
    protected $sdk = '';
    /**
     * Generated from protobuf field <code>repeated string arguments = 3;</code>
     */
    private $arguments;
    /**
     * Generated from protobuf field <code>bytes program_id = 4;</code>
     */
    protected $program_id = '';
    /**
     * Generated from protobuf field <code>.toit.model.Program program = 5;</code>
     */
    protected $program = null;
    /**
     * Generated from protobuf field <code>.toit.model.CompilationResult result = 6;</code>
     */
    protected $result = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>bytes organization_id = 8;</code>
     */
    protected $organization_id = '';
    /**
     * Generated from protobuf field <code>bytes creator_id = 9;</code>
     */
    protected $creator_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $sdk
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $arguments
     *     @type string $program_id
     *     @type \Toit\Model\Program $program
     *     @type \Toit\Model\CompilationResult $result
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type string $organization_id
     *     @type string $creator_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk = 2;</code>
     * @return string
     */
    public function getSdk()
    {
        return $this->sdk;
    }

    /**
     * Generated from protobuf field <code>string sdk = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSdk($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string arguments = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Generated from protobuf field <code>repeated string arguments = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes program_id = 4;</code>
     * @return string
     */
    public function getProgramId()
    {
        return $this->program_id;
    }

    /**
     * Generated from protobuf field <code>bytes program_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramId($var)
    {
        GPBUtil::checkString($var, False);
        $this->program_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Program program = 5;</code>
     * @return \Toit\Model\Program|null
     */
    public function getProgram()
    {
        return $this->program;
    }

    public function hasProgram()
    {
        return isset($this->program);
    }

    public function clearProgram()
    {
        unset($this->program);
    }

    /**
     * Generated from protobuf field <code>.toit.model.Program program = 5;</code>
     * @param \Toit\Model\Program $var
     * @return $this
     */
    public function setProgram($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\Program::class);
        $this->program = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.CompilationResult result = 6;</code>
     * @return \Toit\Model\CompilationResult|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.toit.model.CompilationResult result = 6;</code>
     * @param \Toit\Model\CompilationResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\CompilationResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes organization_id = 8;</code>
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>bytes organization_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkString($var, False);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes creator_id = 9;</code>
     * @return string
     */
    public function getCreatorId()
    {
        return $this->creator_id;
    }

    /**
     * Generated from protobuf field <code>bytes creator_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatorId($var)
    {
        GPBUtil::checkString($var, False);
        $this->creator_id = $var;

        return $this;
    }

}

