<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.ConnectionSetting</code>
 */
class ConnectionSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * This is essentially a one-of but that is not supported when using ubjson
     * encoding as done between the device and the console.
     *
     * Generated from protobuf field <code>.toit.model.WifiSetting wifi = 1;</code>
     */
    protected $wifi = null;
    /**
     * Generated from protobuf field <code>.toit.model.NBIoTSetting nbiot = 2;</code>
     */
    protected $nbiot = null;
    /**
     * Generated from protobuf field <code>.toit.model.EthernetSetting ethernet = 3;</code>
     */
    protected $ethernet = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\WifiSetting $wifi
     *           This is essentially a one-of but that is not supported when using ubjson
     *           encoding as done between the device and the console.
     *     @type \Toit\Model\NBIoTSetting $nbiot
     *     @type \Toit\Model\EthernetSetting $ethernet
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * This is essentially a one-of but that is not supported when using ubjson
     * encoding as done between the device and the console.
     *
     * Generated from protobuf field <code>.toit.model.WifiSetting wifi = 1;</code>
     * @return \Toit\Model\WifiSetting|null
     */
    public function getWifi()
    {
        return $this->wifi;
    }

    public function hasWifi()
    {
        return isset($this->wifi);
    }

    public function clearWifi()
    {
        unset($this->wifi);
    }

    /**
     * This is essentially a one-of but that is not supported when using ubjson
     * encoding as done between the device and the console.
     *
     * Generated from protobuf field <code>.toit.model.WifiSetting wifi = 1;</code>
     * @param \Toit\Model\WifiSetting $var
     * @return $this
     */
    public function setWifi($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\WifiSetting::class);
        $this->wifi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.NBIoTSetting nbiot = 2;</code>
     * @return \Toit\Model\NBIoTSetting|null
     */
    public function getNbiot()
    {
        return $this->nbiot;
    }

    public function hasNbiot()
    {
        return isset($this->nbiot);
    }

    public function clearNbiot()
    {
        unset($this->nbiot);
    }

    /**
     * Generated from protobuf field <code>.toit.model.NBIoTSetting nbiot = 2;</code>
     * @param \Toit\Model\NBIoTSetting $var
     * @return $this
     */
    public function setNbiot($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\NBIoTSetting::class);
        $this->nbiot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.EthernetSetting ethernet = 3;</code>
     * @return \Toit\Model\EthernetSetting|null
     */
    public function getEthernet()
    {
        return $this->ethernet;
    }

    public function hasEthernet()
    {
        return isset($this->ethernet);
    }

    public function clearEthernet()
    {
        unset($this->ethernet);
    }

    /**
     * Generated from protobuf field <code>.toit.model.EthernetSetting ethernet = 3;</code>
     * @param \Toit\Model\EthernetSetting $var
     * @return $this
     */
    public function setEthernet($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\EthernetSetting::class);
        $this->ethernet = $var;

        return $this;
    }

}

