<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.CronSchedule</code>
 */
class CronSchedule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sfixed64 second = 1;</code>
     */
    protected $second = 0;
    /**
     * Generated from protobuf field <code>sfixed64 minute = 2;</code>
     */
    protected $minute = 0;
    /**
     * Generated from protobuf field <code>sfixed64 hour = 3;</code>
     */
    protected $hour = 0;
    /**
     * Generated from protobuf field <code>sfixed64 day_of_month = 4;</code>
     */
    protected $day_of_month = 0;
    /**
     * Generated from protobuf field <code>sfixed64 month = 5;</code>
     */
    protected $month = 0;
    /**
     * Generated from protobuf field <code>sfixed64 day_of_week = 6;</code>
     */
    protected $day_of_week = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_from = 7;</code>
     */
    protected $valid_from = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_to = 8;</code>
     */
    protected $valid_to = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $second
     *     @type int|string $minute
     *     @type int|string $hour
     *     @type int|string $day_of_month
     *     @type int|string $month
     *     @type int|string $day_of_week
     *     @type \Google\Protobuf\Timestamp $valid_from
     *     @type \Google\Protobuf\Timestamp $valid_to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sfixed64 second = 1;</code>
     * @return int|string
     */
    public function getSecond()
    {
        return $this->second;
    }

    /**
     * Generated from protobuf field <code>sfixed64 second = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecond($var)
    {
        GPBUtil::checkInt64($var);
        $this->second = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 minute = 2;</code>
     * @return int|string
     */
    public function getMinute()
    {
        return $this->minute;
    }

    /**
     * Generated from protobuf field <code>sfixed64 minute = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinute($var)
    {
        GPBUtil::checkInt64($var);
        $this->minute = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 hour = 3;</code>
     * @return int|string
     */
    public function getHour()
    {
        return $this->hour;
    }

    /**
     * Generated from protobuf field <code>sfixed64 hour = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHour($var)
    {
        GPBUtil::checkInt64($var);
        $this->hour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 day_of_month = 4;</code>
     * @return int|string
     */
    public function getDayOfMonth()
    {
        return $this->day_of_month;
    }

    /**
     * Generated from protobuf field <code>sfixed64 day_of_month = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDayOfMonth($var)
    {
        GPBUtil::checkInt64($var);
        $this->day_of_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 month = 5;</code>
     * @return int|string
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * Generated from protobuf field <code>sfixed64 month = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMonth($var)
    {
        GPBUtil::checkInt64($var);
        $this->month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 day_of_week = 6;</code>
     * @return int|string
     */
    public function getDayOfWeek()
    {
        return $this->day_of_week;
    }

    /**
     * Generated from protobuf field <code>sfixed64 day_of_week = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDayOfWeek($var)
    {
        GPBUtil::checkInt64($var);
        $this->day_of_week = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_from = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getValidFrom()
    {
        return $this->valid_from;
    }

    public function hasValidFrom()
    {
        return isset($this->valid_from);
    }

    public function clearValidFrom()
    {
        unset($this->valid_from);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_from = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setValidFrom($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->valid_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_to = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getValidTo()
    {
        return $this->valid_to;
    }

    public function hasValidTo()
    {
        return isset($this->valid_to);
    }

    public function clearValidTo()
    {
        unset($this->valid_to);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp valid_to = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setValidTo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->valid_to = $var;

        return $this;
    }

}

