<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/organization.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\Customer\Type instead.
     * @deprecated
     */
    class Customer_Type {}
}
class_exists(Customer\Type::class);
@trigger_error('Toit\Model\Customer_Type is deprecated and will be removed in the next major release. Use Toit\Model\Customer\Type instead', E_USER_DEPRECATED);

