<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\DeviceEvent\Info\Value\Diff instead.
     * @deprecated
     */
    class DeviceEvent_Info_Value_Diff {}
}
class_exists(DeviceEvent\Info\Value\Diff::class);
@trigger_error('Toit\Model\DeviceEvent_Info_Value_Diff is deprecated and will be removed in the next major release. Use Toit\Model\DeviceEvent\Info\Value\Diff instead', E_USER_DEPRECATED);

