<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use UnexpectedValueException;

/**
 * Protobuf type <code>toit.model.DeviceConnectionType</code>
 */
class DeviceConnectionType
{
    /**
     * Generated from protobuf enum <code>DEVICE_CONNECTION_TYPE_UNKNOWN = 0;</code>
     */
    const DEVICE_CONNECTION_TYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>DEVICE_CONNECTION_TYPE_WIFI = 1;</code>
     */
    const DEVICE_CONNECTION_TYPE_WIFI = 1;
    /**
     * Generated from protobuf enum <code>DEVICE_CONNECTION_TYPE_NBIOT = 2;</code>
     */
    const DEVICE_CONNECTION_TYPE_NBIOT = 2;
    /**
     * Generated from protobuf enum <code>DEVICE_CONNECTION_TYPE_OS = 3;</code>
     */
    const DEVICE_CONNECTION_TYPE_OS = 3;
    /**
     * Generated from protobuf enum <code>DEVICE_CONNECTION_TYPE_ETHERNET = 4;</code>
     */
    const DEVICE_CONNECTION_TYPE_ETHERNET = 4;

    private static $valueToName = [
        self::DEVICE_CONNECTION_TYPE_UNKNOWN => 'DEVICE_CONNECTION_TYPE_UNKNOWN',
        self::DEVICE_CONNECTION_TYPE_WIFI => 'DEVICE_CONNECTION_TYPE_WIFI',
        self::DEVICE_CONNECTION_TYPE_NBIOT => 'DEVICE_CONNECTION_TYPE_NBIOT',
        self::DEVICE_CONNECTION_TYPE_OS => 'DEVICE_CONNECTION_TYPE_OS',
        self::DEVICE_CONNECTION_TYPE_ETHERNET => 'DEVICE_CONNECTION_TYPE_ETHERNET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

