<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceHealth</code>
 */
class DeviceHealth extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power power = 1;</code>
     */
    protected $power = null;
    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.BatteryCurve battery_curve = 2;</code>
     */
    protected $battery_curve = null;
    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Connectivity connectivity = 3;</code>
     */
    protected $connectivity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceHealth\Power $power
     *     @type \Toit\Model\DeviceHealth\BatteryCurve $battery_curve
     *     @type \Toit\Model\DeviceHealth\Connectivity $connectivity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power power = 1;</code>
     * @return \Toit\Model\DeviceHealth\Power|null
     */
    public function getPower()
    {
        return $this->power;
    }

    public function hasPower()
    {
        return isset($this->power);
    }

    public function clearPower()
    {
        unset($this->power);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power power = 1;</code>
     * @param \Toit\Model\DeviceHealth\Power $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceHealth\Power::class);
        $this->power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.BatteryCurve battery_curve = 2;</code>
     * @return \Toit\Model\DeviceHealth\BatteryCurve|null
     */
    public function getBatteryCurve()
    {
        return $this->battery_curve;
    }

    public function hasBatteryCurve()
    {
        return isset($this->battery_curve);
    }

    public function clearBatteryCurve()
    {
        unset($this->battery_curve);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.BatteryCurve battery_curve = 2;</code>
     * @param \Toit\Model\DeviceHealth\BatteryCurve $var
     * @return $this
     */
    public function setBatteryCurve($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceHealth\BatteryCurve::class);
        $this->battery_curve = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Connectivity connectivity = 3;</code>
     * @return \Toit\Model\DeviceHealth\Connectivity|null
     */
    public function getConnectivity()
    {
        return $this->connectivity;
    }

    public function hasConnectivity()
    {
        return isset($this->connectivity);
    }

    public function clearConnectivity()
    {
        unset($this->connectivity);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Connectivity connectivity = 3;</code>
     * @param \Toit\Model\DeviceHealth\Connectivity $var
     * @return $this
     */
    public function setConnectivity($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceHealth\Connectivity::class);
        $this->connectivity = $var;

        return $this;
    }

}

