<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceConnectionSettings</code>
 */
class DeviceConnectionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_offline = 1;</code>
     */
    protected $max_offline = null;
    /**
     * Generated from protobuf field <code>repeated .toit.model.ConnectionSetting connections = 2;</code>
     */
    private $connections;
    /**
     * Must be between 0-100
     *
     * Generated from protobuf field <code>uint32 event_queue_threshold = 3;</code>
     */
    protected $event_queue_threshold = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Duration $max_offline
     *     @type \Toit\Model\ConnectionSetting[]|\Google\Protobuf\Internal\RepeatedField $connections
     *     @type int $event_queue_threshold
     *           Must be between 0-100
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_offline = 1;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxOffline()
    {
        return $this->max_offline;
    }

    public function hasMaxOffline()
    {
        return isset($this->max_offline);
    }

    public function clearMaxOffline()
    {
        unset($this->max_offline);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration max_offline = 1;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxOffline($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->max_offline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.ConnectionSetting connections = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConnections()
    {
        return $this->connections;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.ConnectionSetting connections = 2;</code>
     * @param \Toit\Model\ConnectionSetting[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConnections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\ConnectionSetting::class);
        $this->connections = $arr;

        return $this;
    }

    /**
     * Must be between 0-100
     *
     * Generated from protobuf field <code>uint32 event_queue_threshold = 3;</code>
     * @return int
     */
    public function getEventQueueThreshold()
    {
        return $this->event_queue_threshold;
    }

    /**
     * Must be between 0-100
     *
     * Generated from protobuf field <code>uint32 event_queue_threshold = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEventQueueThreshold($var)
    {
        GPBUtil::checkUint32($var);
        $this->event_queue_threshold = $var;

        return $this;
    }

}

