<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use UnexpectedValueException;

/**
 * Protobuf type <code>toit.model.DeviceChangeType</code>
 */
class DeviceChangeType
{
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_UNKNOWN = 0;</code>
     */
    const DEVICE_CHANGE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_ADDED = 1;</code>
     */
    const DEVICE_CHANGE_ADDED = 1;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_DELETED = 2;</code>
     */
    const DEVICE_CHANGE_DELETED = 2;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_CHANGED = 3;</code>
     */
    const DEVICE_CHANGE_CHANGED = 3;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_HEARTBEAT = 4 [deprecated = true];</code>
     */
    const DEVICE_CHANGE_HEARTBEAT = 4;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_CONNECTED = 5;</code>
     */
    const DEVICE_CHANGE_CONNECTED = 5;
    /**
     * Generated from protobuf enum <code>DEVICE_CHANGE_DISCONNECTED = 6;</code>
     */
    const DEVICE_CHANGE_DISCONNECTED = 6;

    private static $valueToName = [
        self::DEVICE_CHANGE_UNKNOWN => 'DEVICE_CHANGE_UNKNOWN',
        self::DEVICE_CHANGE_ADDED => 'DEVICE_CHANGE_ADDED',
        self::DEVICE_CHANGE_DELETED => 'DEVICE_CHANGE_DELETED',
        self::DEVICE_CHANGE_CHANGED => 'DEVICE_CHANGE_CHANGED',
        self::DEVICE_CHANGE_HEARTBEAT => 'DEVICE_CHANGE_HEARTBEAT',
        self::DEVICE_CHANGE_CONNECTED => 'DEVICE_CHANGE_CONNECTED',
        self::DEVICE_CHANGE_DISCONNECTED => 'DEVICE_CHANGE_DISCONNECTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

