<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\DeviceEvent\Info instead.
     * @deprecated
     */
    class DeviceEvent_Info {}
}
class_exists(DeviceEvent\Info::class);
@trigger_error('Toit\Model\DeviceEvent_Info is deprecated and will be removed in the next major release. Use Toit\Model\DeviceEvent\Info instead', E_USER_DEPRECATED);

