<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceBrokerSettings</code>
 */
class DeviceBrokerSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string host = 1;</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>int64 port = 2;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>string cn = 3;</code>
     */
    protected $cn = '';
    /**
     * Generated from protobuf field <code>string protocol = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $protocol = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *     @type int|string $port
     *     @type string $cn
     *     @type string $protocol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 port = 2;</code>
     * @return int|string
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>int64 port = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkInt64($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cn = 3;</code>
     * @return string
     */
    public function getCn()
    {
        return $this->cn;
    }

    /**
     * Generated from protobuf field <code>string cn = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCn($var)
    {
        GPBUtil::checkString($var, True);
        $this->cn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 4 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getProtocol()
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 4 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setProtocol($var)
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->protocol = $var;

        return $this;
    }

}

