<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceModules</code>
 */
class DeviceModules extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceModule cellular = 1;</code>
     */
    protected $cellular = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceModule $cellular
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceModule cellular = 1;</code>
     * @return \Toit\Model\DeviceModule|null
     */
    public function getCellular()
    {
        return $this->cellular;
    }

    public function hasCellular()
    {
        return isset($this->cellular);
    }

    public function clearCellular()
    {
        unset($this->cellular);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceModule cellular = 1;</code>
     * @param \Toit\Model\DeviceModule $var
     * @return $this
     */
    public function setCellular($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceModule::class);
        $this->cellular = $var;

        return $this;
    }

}

