<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\DeviceHealth\Power\Value instead.
     * @deprecated
     */
    class DeviceHealth_Power_Value {}
}
class_exists(DeviceHealth\Power\Value::class);
@trigger_error('Toit\Model\DeviceHealth_Power_Value is deprecated and will be removed in the next major release. Use Toit\Model\DeviceHealth\Power\Value instead', E_USER_DEPRECATED);

