<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\DeviceHealth\Power instead.
     * @deprecated
     */
    class DeviceHealth_Power {}
}
class_exists(DeviceHealth\Power::class);
@trigger_error('Toit\Model\DeviceHealth_Power is deprecated and will be removed in the next major release. Use Toit\Model\DeviceHealth\Power instead', E_USER_DEPRECATED);

