<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.GPIOTrigger</code>
 */
class GPIOTrigger extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .toit.model.GPIOTrigger.Pin pins = 1;</code>
     */
    private $pins;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\GPIOTrigger\Pin[]|\Google\Protobuf\Internal\RepeatedField $pins
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.GPIOTrigger.Pin pins = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPins()
    {
        return $this->pins;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.GPIOTrigger.Pin pins = 1;</code>
     * @param \Toit\Model\GPIOTrigger\Pin[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\GPIOTrigger\Pin::class);
        $this->pins = $arr;

        return $this;
    }

}

