<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\GPIOTrigger\Pin instead.
     * @deprecated
     */
    class GPIOTrigger_Pin {}
}
class_exists(GPIOTrigger\Pin::class);
@trigger_error('Toit\Model\GPIOTrigger_Pin is deprecated and will be removed in the next major release. Use Toit\Model\GPIOTrigger\Pin instead', E_USER_DEPRECATED);

