<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\GPIOTrigger\Pin\Level instead.
     * @deprecated
     */
    class GPIOTrigger_Pin_Level {}
}
class_exists(GPIOTrigger\Pin\Level::class);
@trigger_error('Toit\Model\GPIOTrigger_Pin_Level is deprecated and will be removed in the next major release. Use Toit\Model\GPIOTrigger\Pin\Level instead', E_USER_DEPRECATED);

