<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.HardwareIdentityInfo</code>
 */
class HardwareIdentityInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string factory_sdk_version = 1;</code>
     */
    protected $factory_sdk_version = '';
    /**
     * Generated from protobuf field <code>bytes flashed_by = 2;</code>
     */
    protected $flashed_by = '';
    /**
     * Generated from protobuf field <code>string iccid = 3;</code>
     */
    protected $iccid = '';
    /**
     * Generated from protobuf field <code>string chip_id = 4;</code>
     */
    protected $chip_id = '';
    /**
     * Generated from protobuf field <code>string factory_device_model = 5;</code>
     */
    protected $factory_device_model = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $factory_sdk_version
     *     @type string $flashed_by
     *     @type string $iccid
     *     @type string $chip_id
     *     @type string $factory_device_model
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string factory_sdk_version = 1;</code>
     * @return string
     */
    public function getFactorySdkVersion()
    {
        return $this->factory_sdk_version;
    }

    /**
     * Generated from protobuf field <code>string factory_sdk_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFactorySdkVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->factory_sdk_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes flashed_by = 2;</code>
     * @return string
     */
    public function getFlashedBy()
    {
        return $this->flashed_by;
    }

    /**
     * Generated from protobuf field <code>bytes flashed_by = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFlashedBy($var)
    {
        GPBUtil::checkString($var, False);
        $this->flashed_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iccid = 3;</code>
     * @return string
     */
    public function getIccid()
    {
        return $this->iccid;
    }

    /**
     * Generated from protobuf field <code>string iccid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIccid($var)
    {
        GPBUtil::checkString($var, True);
        $this->iccid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chip_id = 4;</code>
     * @return string
     */
    public function getChipId()
    {
        return $this->chip_id;
    }

    /**
     * Generated from protobuf field <code>string chip_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChipId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chip_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string factory_device_model = 5;</code>
     * @return string
     */
    public function getFactoryDeviceModel()
    {
        return $this->factory_device_model;
    }

    /**
     * Generated from protobuf field <code>string factory_device_model = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFactoryDeviceModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->factory_device_model = $var;

        return $this;
    }

}

