<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.HardwareToDeviceInfo</code>
 */
class HardwareToDeviceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     */
    protected $hardware_id = '';
    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp bound = 3;</code>
     */
    protected $bound = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp unbound = 4;</code>
     */
    protected $unbound = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hardware_id
     *     @type string $device_id
     *     @type \Google\Protobuf\Timestamp $bound
     *     @type \Google\Protobuf\Timestamp $unbound
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     * @return string
     */
    public function getHardwareId()
    {
        return $this->hardware_id;
    }

    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHardwareId($var)
    {
        GPBUtil::checkString($var, False);
        $this->hardware_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp bound = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getBound()
    {
        return $this->bound;
    }

    public function hasBound()
    {
        return isset($this->bound);
    }

    public function clearBound()
    {
        unset($this->bound);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp bound = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setBound($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->bound = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp unbound = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUnbound()
    {
        return $this->unbound;
    }

    public function hasUnbound()
    {
        return isset($this->unbound);
    }

    public function clearUnbound()
    {
        unset($this->unbound);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp unbound = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUnbound($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->unbound = $var;

        return $this;
    }

}

