<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.HardwareIdentity</code>
 */
class HardwareIdentity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     */
    protected $hardware_id = '';
    /**
     * Generated from protobuf field <code>int64 sequence_number = 2;</code>
     */
    protected $sequence_number = 0;
    /**
     * Generated from protobuf field <code>string batch = 3;</code>
     */
    protected $batch = '';
    /**
     * Generated from protobuf field <code>bytes private_key = 4;</code>
     */
    protected $private_key = '';
    /**
     * Generated from protobuf field <code>bytes certificate = 5;</code>
     */
    protected $certificate = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hardware_id
     *     @type int|string $sequence_number
     *     @type string $batch
     *     @type string $private_key
     *     @type string $certificate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     * @return string
     */
    public function getHardwareId()
    {
        return $this->hardware_id;
    }

    /**
     * Generated from protobuf field <code>bytes hardware_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHardwareId($var)
    {
        GPBUtil::checkString($var, False);
        $this->hardware_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sequence_number = 2;</code>
     * @return int|string
     */
    public function getSequenceNumber()
    {
        return $this->sequence_number;
    }

    /**
     * Generated from protobuf field <code>int64 sequence_number = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequenceNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->sequence_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string batch = 3;</code>
     * @return string
     */
    public function getBatch()
    {
        return $this->batch;
    }

    /**
     * Generated from protobuf field <code>string batch = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBatch($var)
    {
        GPBUtil::checkString($var, True);
        $this->batch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes private_key = 4;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>bytes private_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 5;</code>
     * @return string
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->certificate = $var;

        return $this;
    }

}

