<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/data.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.HistogramMetricData</code>
 */
class HistogramMetricData extends \Google\Protobuf\Internal\Message
{
    /**
     * name_index references the name in the names list in MetricsData.
     *
     * Generated from protobuf field <code>uint32 name_index = 1;</code>
     */
    protected $name_index = 0;
    /**
     * Generated from protobuf field <code>map<uint32, double> values = 2;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>map<uint32, uint32> tags = 3;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.toit.model.MetricsData.Level level = 4;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $name_index
     *           name_index references the name in the names list in MetricsData.
     *     @type array|\Google\Protobuf\Internal\MapField $values
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     *     @type int $level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * name_index references the name in the names list in MetricsData.
     *
     * Generated from protobuf field <code>uint32 name_index = 1;</code>
     * @return int
     */
    public function getNameIndex()
    {
        return $this->name_index;
    }

    /**
     * name_index references the name in the names list in MetricsData.
     *
     * Generated from protobuf field <code>uint32 name_index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNameIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->name_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, double> values = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>map<uint32, double> values = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, uint32> tags = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<uint32, uint32> tags = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.MetricsData.Level level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>.toit.model.MetricsData.Level level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\MetricsData\Level::class);
        $this->level = $var;

        return $this;
    }

}

