<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.JobConfig</code>
 */
class JobConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes job_id = 8;</code>
     */
    protected $job_id = '';
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bytes compilation_id = 2;</code>
     */
    protected $compilation_id = '';
    /**
     * Generated from protobuf field <code>.toit.model.JobGoalState goal_state = 3;</code>
     */
    protected $goal_state = 0;
    /**
     * Generated from protobuf field <code>.toit.model.JobResources resources = 4;</code>
     */
    protected $resources = null;
    /**
     * Generated from protobuf field <code>.toit.model.JobTriggers triggers = 5;</code>
     */
    protected $triggers = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 6;</code>
     */
    protected $created = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 7;</code>
     */
    protected $updated = null;
    /**
     * Generated from protobuf field <code>.toit.model.CompilationInfo compilation_info = 10;</code>
     */
    protected $compilation_info = null;
    /**
     * Generated from protobuf field <code>.toit.model.JobPubSub pubsub = 11;</code>
     */
    protected $pubsub = null;
    /**
     * Generated from protobuf field <code>repeated .toit.model.JobFile files = 12;</code>
     */
    private $files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *     @type string $name
     *     @type string $compilation_id
     *     @type int $goal_state
     *     @type \Toit\Model\JobResources $resources
     *     @type \Toit\Model\JobTriggers $triggers
     *     @type \Google\Protobuf\Timestamp $created
     *     @type \Google\Protobuf\Timestamp $updated
     *     @type \Toit\Model\CompilationInfo $compilation_info
     *     @type \Toit\Model\JobPubSub $pubsub
     *     @type \Toit\Model\JobFile[]|\Google\Protobuf\Internal\RepeatedField $files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes job_id = 8;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Generated from protobuf field <code>bytes job_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, False);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes compilation_id = 2;</code>
     * @return string
     */
    public function getCompilationId()
    {
        return $this->compilation_id;
    }

    /**
     * Generated from protobuf field <code>bytes compilation_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompilationId($var)
    {
        GPBUtil::checkString($var, False);
        $this->compilation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobGoalState goal_state = 3;</code>
     * @return int
     */
    public function getGoalState()
    {
        return $this->goal_state;
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobGoalState goal_state = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGoalState($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\JobGoalState::class);
        $this->goal_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobResources resources = 4;</code>
     * @return \Toit\Model\JobResources|null
     */
    public function getResources()
    {
        return $this->resources;
    }

    public function hasResources()
    {
        return isset($this->resources);
    }

    public function clearResources()
    {
        unset($this->resources);
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobResources resources = 4;</code>
     * @param \Toit\Model\JobResources $var
     * @return $this
     */
    public function setResources($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\JobResources::class);
        $this->resources = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobTriggers triggers = 5;</code>
     * @return \Toit\Model\JobTriggers|null
     */
    public function getTriggers()
    {
        return $this->triggers;
    }

    public function hasTriggers()
    {
        return isset($this->triggers);
    }

    public function clearTriggers()
    {
        unset($this->triggers);
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobTriggers triggers = 5;</code>
     * @param \Toit\Model\JobTriggers $var
     * @return $this
     */
    public function setTriggers($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\JobTriggers::class);
        $this->triggers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreated()
    {
        return $this->created;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    public function hasUpdated()
    {
        return isset($this->updated);
    }

    public function clearUpdated()
    {
        unset($this->updated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.CompilationInfo compilation_info = 10;</code>
     * @return \Toit\Model\CompilationInfo|null
     */
    public function getCompilationInfo()
    {
        return $this->compilation_info;
    }

    public function hasCompilationInfo()
    {
        return isset($this->compilation_info);
    }

    public function clearCompilationInfo()
    {
        unset($this->compilation_info);
    }

    /**
     * Generated from protobuf field <code>.toit.model.CompilationInfo compilation_info = 10;</code>
     * @param \Toit\Model\CompilationInfo $var
     * @return $this
     */
    public function setCompilationInfo($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\CompilationInfo::class);
        $this->compilation_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobPubSub pubsub = 11;</code>
     * @return \Toit\Model\JobPubSub|null
     */
    public function getPubsub()
    {
        return $this->pubsub;
    }

    public function hasPubsub()
    {
        return isset($this->pubsub);
    }

    public function clearPubsub()
    {
        unset($this->pubsub);
    }

    /**
     * Generated from protobuf field <code>.toit.model.JobPubSub pubsub = 11;</code>
     * @param \Toit\Model\JobPubSub $var
     * @return $this
     */
    public function setPubsub($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\JobPubSub::class);
        $this->pubsub = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.JobFile files = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.JobFile files = 12;</code>
     * @param \Toit\Model\JobFile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\JobFile::class);
        $this->files = $arr;

        return $this;
    }

}

