<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\JobPubSub\Subscription instead.
     * @deprecated
     */
    class JobPubSub_Subscription {}
}
class_exists(JobPubSub\Subscription::class);
@trigger_error('Toit\Model\JobPubSub_Subscription is deprecated and will be removed in the next major release. Use Toit\Model\JobPubSub\Subscription instead', E_USER_DEPRECATED);

