<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/app.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\JobSpec\PubSub instead.
     * @deprecated
     */
    class JobSpec_PubSub {}
}
class_exists(JobSpec\PubSub::class);
@trigger_error('Toit\Model\JobSpec_PubSub is deprecated and will be removed in the next major release. Use Toit\Model\JobSpec\PubSub instead', E_USER_DEPRECATED);

