<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/job.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.MemoryResource</code>
 */
class MemoryResource extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 memory = 1;</code>
     */
    protected $memory = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $memory
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 memory = 1;</code>
     * @return int|string
     */
    public function getMemory()
    {
        return $this->memory;
    }

    /**
     * Generated from protobuf field <code>int64 memory = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemory($var)
    {
        GPBUtil::checkInt64($var);
        $this->memory = $var;

        return $this;
    }

}

