<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/organization.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.Organization</code>
 */
class Organization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string default_sdk = 3;</code>
     */
    protected $default_sdk = '';
    /**
     * Generated from protobuf field <code>string email = 4;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string city = 5;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string country = 6;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string phone_number = 7;</code>
     */
    protected $phone_number = '';
    /**
     * Not used
     *
     * Generated from protobuf field <code>string cvr_number = 8;</code>
     */
    protected $cvr_number = '';
    /**
     * Generated from protobuf field <code>.toit.model.Tier.Type tier = 9;</code>
     */
    protected $tier = 0;
    /**
     * Generated from protobuf field <code>.toit.model.PaymentDetails payment_details = 10;</code>
     */
    protected $payment_details = null;
    /**
     * Generated from protobuf field <code>string address_line = 11;</code>
     */
    protected $address_line = '';
    /**
     * Generated from protobuf field <code>string postal_code = 12;</code>
     */
    protected $postal_code = '';
    /**
     * Generated from protobuf field <code>string vat_number = 13;</code>
     */
    protected $vat_number = '';
    /**
     * Generated from protobuf field <code>string vat_country_code = 14;</code>
     */
    protected $vat_country_code = '';
    /**
     * Generated from protobuf field <code>.toit.model.Customer.Type customer = 15;</code>
     */
    protected $customer = 0;
    /**
     * Generated from protobuf field <code>uint64 hwid_quota = 16;</code>
     */
    protected $hwid_quota = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $default_sdk
     *     @type string $email
     *     @type string $city
     *     @type string $country
     *     @type string $phone_number
     *     @type string $cvr_number
     *           Not used
     *     @type int $tier
     *     @type \Toit\Model\PaymentDetails $payment_details
     *     @type string $address_line
     *     @type string $postal_code
     *     @type string $vat_number
     *     @type string $vat_country_code
     *     @type int $customer
     *     @type int|string $hwid_quota
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_sdk = 3;</code>
     * @return string
     */
    public function getDefaultSdk()
    {
        return $this->default_sdk;
    }

    /**
     * Generated from protobuf field <code>string default_sdk = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultSdk($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_sdk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 5;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone_number = 7;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Generated from protobuf field <code>string phone_number = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string cvr_number = 8;</code>
     * @return string
     */
    public function getCvrNumber()
    {
        return $this->cvr_number;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string cvr_number = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCvrNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->cvr_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Tier.Type tier = 9;</code>
     * @return int
     */
    public function getTier()
    {
        return $this->tier;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Tier.Type tier = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTier($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\Tier\Type::class);
        $this->tier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.PaymentDetails payment_details = 10;</code>
     * @return \Toit\Model\PaymentDetails|null
     */
    public function getPaymentDetails()
    {
        return $this->payment_details;
    }

    public function hasPaymentDetails()
    {
        return isset($this->payment_details);
    }

    public function clearPaymentDetails()
    {
        unset($this->payment_details);
    }

    /**
     * Generated from protobuf field <code>.toit.model.PaymentDetails payment_details = 10;</code>
     * @param \Toit\Model\PaymentDetails $var
     * @return $this
     */
    public function setPaymentDetails($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\PaymentDetails::class);
        $this->payment_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address_line = 11;</code>
     * @return string
     */
    public function getAddressLine()
    {
        return $this->address_line;
    }

    /**
     * Generated from protobuf field <code>string address_line = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine($var)
    {
        GPBUtil::checkString($var, True);
        $this->address_line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 12;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vat_number = 13;</code>
     * @return string
     */
    public function getVatNumber()
    {
        return $this->vat_number;
    }

    /**
     * Generated from protobuf field <code>string vat_number = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setVatNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->vat_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vat_country_code = 14;</code>
     * @return string
     */
    public function getVatCountryCode()
    {
        return $this->vat_country_code;
    }

    /**
     * Generated from protobuf field <code>string vat_country_code = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setVatCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->vat_country_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Customer.Type customer = 15;</code>
     * @return int
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Customer.Type customer = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setCustomer($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\Customer\Type::class);
        $this->customer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 hwid_quota = 16;</code>
     * @return int|string
     */
    public function getHwidQuota()
    {
        return $this->hwid_quota;
    }

    /**
     * Generated from protobuf field <code>uint64 hwid_quota = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHwidQuota($var)
    {
        GPBUtil::checkUint64($var);
        $this->hwid_quota = $var;

        return $this;
    }

}

