<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/organization.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.PaymentDetails</code>
 */
class PaymentDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string last4 = 1;</code>
     */
    protected $last4 = '';
    /**
     * Not used
     *
     * Generated from protobuf field <code>string expiry = 2;</code>
     */
    protected $expiry = '';
    /**
     * Generated from protobuf field <code>string expiry_month = 3;</code>
     */
    protected $expiry_month = '';
    /**
     * Generated from protobuf field <code>string expiry_year = 4;</code>
     */
    protected $expiry_year = '';
    /**
     * Generated from protobuf field <code>string brand = 5;</code>
     */
    protected $brand = '';
    /**
     * Generated from protobuf field <code>string country_code = 6;</code>
     */
    protected $country_code = '';
    /**
     * Generated from protobuf field <code>string cvc_check = 7;</code>
     */
    protected $cvc_check = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $last4
     *     @type string $expiry
     *           Not used
     *     @type string $expiry_month
     *     @type string $expiry_year
     *     @type string $brand
     *     @type string $country_code
     *     @type string $cvc_check
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string last4 = 1;</code>
     * @return string
     */
    public function getLast4()
    {
        return $this->last4;
    }

    /**
     * Generated from protobuf field <code>string last4 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLast4($var)
    {
        GPBUtil::checkString($var, True);
        $this->last4 = $var;

        return $this;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string expiry = 2;</code>
     * @return string
     */
    public function getExpiry()
    {
        return $this->expiry;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string expiry = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpiry($var)
    {
        GPBUtil::checkString($var, True);
        $this->expiry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expiry_month = 3;</code>
     * @return string
     */
    public function getExpiryMonth()
    {
        return $this->expiry_month;
    }

    /**
     * Generated from protobuf field <code>string expiry_month = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExpiryMonth($var)
    {
        GPBUtil::checkString($var, True);
        $this->expiry_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expiry_year = 4;</code>
     * @return string
     */
    public function getExpiryYear()
    {
        return $this->expiry_year;
    }

    /**
     * Generated from protobuf field <code>string expiry_year = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExpiryYear($var)
    {
        GPBUtil::checkString($var, True);
        $this->expiry_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brand = 5;</code>
     * @return string
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * Generated from protobuf field <code>string brand = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBrand($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country_code = 6;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * Generated from protobuf field <code>string country_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cvc_check = 7;</code>
     * @return string
     */
    public function getCvcCheck()
    {
        return $this->cvc_check;
    }

    /**
     * Generated from protobuf field <code>string cvc_check = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCvcCheck($var)
    {
        GPBUtil::checkString($var, True);
        $this->cvc_check = $var;

        return $this;
    }

}

