<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/program.proto

namespace Toit\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.ReleaseLevel</code>
 */
class ReleaseLevel extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Program::initOnce();
        parent::__construct($data);
    }

}

