<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/organization.proto

namespace Toit\Model;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\User\State instead.
     * @deprecated
     */
    class User_State {}
}
class_exists(User\State::class);
@trigger_error('Toit\Model\User_State is deprecated and will be removed in the next major release. Use Toit\Model\User\State instead', E_USER_DEPRECATED);

