<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api\AnalyzeRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.AnalyzeRequest.Source</code>
 */
class Source extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sdk_name = 1;</code>
     */
    protected $sdk_name = '';
    /**
     * Generated from protobuf field <code>string entry_filename = 2;</code>
     */
    protected $entry_filename = '';
    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 3;</code>
     */
    private $sources;
    /**
     * Generated from protobuf field <code>repeated string args = 4;</code>
     */
    private $args;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sdk_name
     *     @type string $entry_filename
     *     @type array|\Google\Protobuf\Internal\MapField $sources
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $args
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sdk_name = 1;</code>
     * @return string
     */
    public function getSdkName()
    {
        return $this->sdk_name;
    }

    /**
     * Generated from protobuf field <code>string sdk_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdk_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entry_filename = 2;</code>
     * @return string
     */
    public function getEntryFilename()
    {
        return $this->entry_filename;
    }

    /**
     * Generated from protobuf field <code>string entry_filename = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntryFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->entry_filename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSources()
    {
        return $this->sources;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSources($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->sources = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string args = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated string args = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Source::class, \Toit\Api\AnalyzeRequest_Source::class);

