<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/data.proto

namespace Toit\Model\MetricsData;

use UnexpectedValueException;

/**
 * Protobuf type <code>toit.model.MetricsData.Level</code>
 */
class Level
{
    /**
     * Generated from protobuf enum <code>DEBUG_LEVEL = 0;</code>
     */
    const DEBUG_LEVEL = 0;
    /**
     * Generated from protobuf enum <code>INFO_LEVEL = 5;</code>
     */
    const INFO_LEVEL = 5;
    /**
     * Generated from protobuf enum <code>CRITICAL_LEVEL = 10;</code>
     */
    const CRITICAL_LEVEL = 10;

    private static $valueToName = [
        self::DEBUG_LEVEL => 'DEBUG_LEVEL',
        self::INFO_LEVEL => 'INFO_LEVEL',
        self::CRITICAL_LEVEL => 'CRITICAL_LEVEL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Level::class, \Toit\Model\MetricsData_Level::class);

