<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model\DeviceEvent\Info;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceEvent.Info.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceEvent\Info\Value\Primitive $primitive
     *     @type \Toit\Model\DeviceEvent\Info\Value\Diff $diff
     *     @type \Toit\Model\DeviceEvent\Info\Value\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive primitive = 1;</code>
     * @return \Toit\Model\DeviceEvent\Info\Value\Primitive|null
     */
    public function getPrimitive()
    {
        return $this->readOneof(1);
    }

    public function hasPrimitive()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive primitive = 1;</code>
     * @param \Toit\Model\DeviceEvent\Info\Value\Primitive $var
     * @return $this
     */
    public function setPrimitive($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceEvent\Info\Value\Primitive::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Diff diff = 2;</code>
     * @return \Toit\Model\DeviceEvent\Info\Value\Diff|null
     */
    public function getDiff()
    {
        return $this->readOneof(2);
    }

    public function hasDiff()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Diff diff = 2;</code>
     * @param \Toit\Model\DeviceEvent\Info\Value\Diff $var
     * @return $this
     */
    public function setDiff($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceEvent\Info\Value\Diff::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Error error = 3;</code>
     * @return \Toit\Model\DeviceEvent\Info\Value\Error|null
     */
    public function getError()
    {
        return $this->readOneof(3);
    }

    public function hasError()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Error error = 3;</code>
     * @param \Toit\Model\DeviceEvent\Info\Value\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceEvent\Info\Value\Error::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Value::class, \Toit\Model\DeviceEvent_Info_Value::class);

