<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model\DeviceHealth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceHealth.BatteryCurve</code>
 */
class BatteryCurve extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double slope = 1;</code>
     */
    protected $slope = 0.0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     */
    protected $last_updated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $slope
     *     @type \Google\Protobuf\Timestamp $last_updated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double slope = 1;</code>
     * @return float
     */
    public function getSlope()
    {
        return $this->slope;
    }

    /**
     * Generated from protobuf field <code>double slope = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setSlope($var)
    {
        GPBUtil::checkDouble($var);
        $this->slope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastUpdated()
    {
        return $this->last_updated;
    }

    public function hasLastUpdated()
    {
        return isset($this->last_updated);
    }

    public function clearLastUpdated()
    {
        unset($this->last_updated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_updated = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BatteryCurve::class, \Toit\Model\DeviceHealth_BatteryCurve::class);

