<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model\DeviceHealth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceHealth.Power</code>
 */
class Power extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power.Value value = 1;</code>
     */
    protected $value = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     */
    protected $last_updated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceHealth\Power\Value $value
     *     @type \Google\Protobuf\Timestamp $last_updated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power.Value value = 1;</code>
     * @return \Toit\Model\DeviceHealth\Power\Value|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceHealth.Power.Value value = 1;</code>
     * @param \Toit\Model\DeviceHealth\Power\Value $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceHealth\Power\Value::class);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastUpdated()
    {
        return $this->last_updated;
    }

    public function hasLastUpdated()
    {
        return isset($this->last_updated);
    }

    public function clearLastUpdated()
    {
        unset($this->last_updated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_updated = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Power::class, \Toit\Model\DeviceHealth_Power::class);

