<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/pubsub/subscribe.proto

namespace Toit\Api\Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.pubsub.CreateSubscriptionResponse</code>
 */
class CreateSubscriptionResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Pubsub\Subscribe::initOnce();
        parent::__construct($data);
    }

}

