<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/app.proto

namespace Toit\Api\ListAppsRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>toit.api.ListAppsRequest.OrderBy</code>
 */
class OrderBy
{
    /**
     * Generated from protobuf enum <code>ADDED_ID = 0;</code>
     */
    const ADDED_ID = 0;
    /**
     * Generated from protobuf enum <code>NAME = 1;</code>
     */
    const NAME = 1;

    private static $valueToName = [
        self::ADDED_ID => 'ADDED_ID',
        self::NAME => 'NAME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OrderBy::class, \Toit\Api\ListAppsRequest_OrderBy::class);

