<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.AnalyzeResponse</code>
 */
class AnalyzeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes stderr = 1;</code>
     */
    protected $stderr = '';
    /**
     * Generated from protobuf field <code>.toit.api.AnalyzeResponse.Features features = 2;</code>
     */
    protected $features = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stderr
     *     @type \Toit\Api\AnalyzeResponse\Features $features
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes stderr = 1;</code>
     * @return string
     */
    public function getStderr()
    {
        return $this->stderr;
    }

    /**
     * Generated from protobuf field <code>bytes stderr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStderr($var)
    {
        GPBUtil::checkString($var, False);
        $this->stderr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.api.AnalyzeResponse.Features features = 2;</code>
     * @return \Toit\Api\AnalyzeResponse\Features|null
     */
    public function getFeatures()
    {
        return $this->features;
    }

    public function hasFeatures()
    {
        return isset($this->features);
    }

    public function clearFeatures()
    {
        unset($this->features);
    }

    /**
     * Generated from protobuf field <code>.toit.api.AnalyzeResponse.Features features = 2;</code>
     * @param \Toit\Api\AnalyzeResponse\Features $var
     * @return $this
     */
    public function setFeatures($var)
    {
        GPBUtil::checkMessage($var, \Toit\Api\AnalyzeResponse\Features::class);
        $this->features = $var;

        return $this;
    }

}

