<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.AnalyzeRequest</code>
 */
class AnalyzeRequest extends \Google\Protobuf\Internal\Message
{
    protected $program;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Api\AnalyzeRequest\Source $source
     *     @type string $compilation_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.api.AnalyzeRequest.Source source = 1;</code>
     * @return \Toit\Api\AnalyzeRequest\Source|null
     */
    public function getSource()
    {
        return $this->readOneof(1);
    }

    public function hasSource()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.toit.api.AnalyzeRequest.Source source = 1;</code>
     * @param \Toit\Api\AnalyzeRequest\Source $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkMessage($var, \Toit\Api\AnalyzeRequest\Source::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes compilation_id = 2;</code>
     * @return string
     */
    public function getCompilationId()
    {
        return $this->readOneof(2);
    }

    public function hasCompilationId()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bytes compilation_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompilationId($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getProgram()
    {
        return $this->whichOneof("program");
    }

}

