<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/auth.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.AuthResponse</code>
 */
class AuthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes access_token = 1;</code>
     */
    protected $access_token = '';
    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     */
    protected $token_type = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expires_in = 3;</code>
     */
    protected $expires_in = null;
    /**
     * Generated from protobuf field <code>bytes refresh_token = 4;</code>
     */
    protected $refresh_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_token
     *     @type string $token_type
     *     @type \Google\Protobuf\Duration $expires_in
     *     @type string $refresh_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes access_token = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>bytes access_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     * @return string
     */
    public function getTokenType()
    {
        return $this->token_type;
    }

    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expires_in = 3;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getExpiresIn()
    {
        return $this->expires_in;
    }

    public function hasExpiresIn()
    {
        return isset($this->expires_in);
    }

    public function clearExpiresIn()
    {
        unset($this->expires_in);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expires_in = 3;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setExpiresIn($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->expires_in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes refresh_token = 4;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refresh_token;
    }

    /**
     * Generated from protobuf field <code>bytes refresh_token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->refresh_token = $var;

        return $this;
    }

}

