<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.CompileRequest</code>
 */
class CompileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     */
    protected $program_name = '';
    /**
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     */
    protected $sdk_name = '';
    /**
     * Generated from protobuf field <code>string entry_filename = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $entry_filename = '';
    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 4 [deprecated = true];</code>
     * @deprecated
     */
    private $sources;
    /**
     * Generated from protobuf field <code>repeated string args = 5;</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>.toit.api.ProgramSource source = 6;</code>
     */
    protected $source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $program_name
     *     @type string $sdk_name
     *     @type string $entry_filename
     *     @type array|\Google\Protobuf\Internal\MapField $sources
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $args
     *     @type \Toit\Api\ProgramSource $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     * @return string
     */
    public function getProgramName()
    {
        return $this->program_name;
    }

    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramName($var)
    {
        GPBUtil::checkString($var, True);
        $this->program_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     * @return string
     */
    public function getSdkName()
    {
        return $this->sdk_name;
    }

    /**
     * Generated from protobuf field <code>string sdk_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdk_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entry_filename = 3 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getEntryFilename()
    {
        @trigger_error('entry_filename is deprecated.', E_USER_DEPRECATED);
        return $this->entry_filename;
    }

    /**
     * Generated from protobuf field <code>string entry_filename = 3 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setEntryFilename($var)
    {
        @trigger_error('entry_filename is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->entry_filename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 4 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\MapField
     * @deprecated
     */
    public function getSources()
    {
        @trigger_error('sources is deprecated.', E_USER_DEPRECATED);
        return $this->sources;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> sources = 4 [deprecated = true];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     * @deprecated
     */
    public function setSources($var)
    {
        @trigger_error('sources is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->sources = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string args = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated string args = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.api.ProgramSource source = 6;</code>
     * @return \Toit\Api\ProgramSource|null
     */
    public function getSource()
    {
        return $this->source;
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * Generated from protobuf field <code>.toit.api.ProgramSource source = 6;</code>
     * @param \Toit\Api\ProgramSource $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkMessage($var, \Toit\Api\ProgramSource::class);
        $this->source = $var;

        return $this;
    }

}

