<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\LoggingLevel instead.
     * @deprecated
     */
    class ConfigChange_LoggingLevel {}
}
class_exists(ConfigChange\LoggingLevel::class);
@trigger_error('Toit\Api\ConfigChange_LoggingLevel is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\LoggingLevel instead', E_USER_DEPRECATED);

