<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\Connections instead.
     * @deprecated
     */
    class ConfigChange_Connections {}
}
class_exists(ConfigChange\Connections::class);
@trigger_error('Toit\Api\ConfigChange_Connections is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\Connections instead', E_USER_DEPRECATED);

