<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\EventQueueThreshold instead.
     * @deprecated
     */
    class ConfigChange_EventQueueThreshold {}
}
class_exists(ConfigChange\EventQueueThreshold::class);
@trigger_error('Toit\Api\ConfigChange_EventQueueThreshold is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\EventQueueThreshold instead', E_USER_DEPRECATED);

