<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\MetricsLevel instead.
     * @deprecated
     */
    class ConfigChange_MetricsLevel {}
}
class_exists(ConfigChange\MetricsLevel::class);
@trigger_error('Toit\Api\ConfigChange_MetricsLevel is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\MetricsLevel instead', E_USER_DEPRECATED);

