<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ConfigureDeviceRequest</code>
 */
class ConfigureDeviceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>repeated .toit.api.ConfigChange config_changes = 8;</code>
     */
    private $config_changes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type \Toit\Api\ConfigChange[]|\Google\Protobuf\Internal\RepeatedField $config_changes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.api.ConfigChange config_changes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfigChanges()
    {
        return $this->config_changes;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.api.ConfigChange config_changes = 8;</code>
     * @param \Toit\Api\ConfigChange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfigChanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Api\ConfigChange::class);
        $this->config_changes = $arr;

        return $this;
    }

}

