<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\SDK instead.
     * @deprecated
     */
    class ConfigChange_SDK {}
}
class_exists(ConfigChange\SDK::class);
@trigger_error('Toit\Api\ConfigChange_SDK is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\SDK instead', E_USER_DEPRECATED);

