<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ConfigChange\Name instead.
     * @deprecated
     */
    class ConfigChange_Name {}
}
class_exists(ConfigChange\Name::class);
@trigger_error('Toit\Api\ConfigChange_Name is deprecated and will be removed in the next major release. Use Toit\Api\ConfigChange\Name instead', E_USER_DEPRECATED);

