<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/auth.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\CreateOrganizationRequest\Organization instead.
     * @deprecated
     */
    class CreateOrganizationRequest_Organization {}
}
class_exists(CreateOrganizationRequest\Organization::class);
@trigger_error('Toit\Api\CreateOrganizationRequest_Organization is deprecated and will be removed in the next major release. Use Toit\Api\CreateOrganizationRequest\Organization instead', E_USER_DEPRECATED);

