<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/app.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\CreateAppRequest\Files instead.
     * @deprecated
     */
    class CreateAppRequest_Files {}
}
class_exists(CreateAppRequest\Files::class);
@trigger_error('Toit\Api\CreateAppRequest_Files is deprecated and will be removed in the next major release. Use Toit\Api\CreateAppRequest\Files instead', E_USER_DEPRECATED);

