<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/user.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.CreatePaymentSubscriptionRequest</code>
 */
class CreatePaymentSubscriptionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not used
     *
     * Generated from protobuf field <code>string billing_email = 1;</code>
     */
    protected $billing_email = '';
    /**
     * Generated from protobuf field <code>string card_holder_name = 2;</code>
     */
    protected $card_holder_name = '';
    /**
     * Generated from protobuf field <code>int32 card_cvc = 3;</code>
     */
    protected $card_cvc = 0;
    /**
     * Generated from protobuf field <code>int32 card_expiry_month = 4;</code>
     */
    protected $card_expiry_month = 0;
    /**
     * Generated from protobuf field <code>int32 card_expiry_year = 5;</code>
     */
    protected $card_expiry_year = 0;
    /**
     * Generated from protobuf field <code>uint64 card_number = 6;</code>
     */
    protected $card_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $billing_email
     *           Not used
     *     @type string $card_holder_name
     *     @type int $card_cvc
     *     @type int $card_expiry_month
     *     @type int $card_expiry_year
     *     @type int|string $card_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string billing_email = 1;</code>
     * @return string
     */
    public function getBillingEmail()
    {
        return $this->billing_email;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string billing_email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBillingEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->billing_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_holder_name = 2;</code>
     * @return string
     */
    public function getCardHolderName()
    {
        return $this->card_holder_name;
    }

    /**
     * Generated from protobuf field <code>string card_holder_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCardHolderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_holder_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 card_cvc = 3;</code>
     * @return int
     */
    public function getCardCvc()
    {
        return $this->card_cvc;
    }

    /**
     * Generated from protobuf field <code>int32 card_cvc = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCardCvc($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_cvc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 card_expiry_month = 4;</code>
     * @return int
     */
    public function getCardExpiryMonth()
    {
        return $this->card_expiry_month;
    }

    /**
     * Generated from protobuf field <code>int32 card_expiry_month = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCardExpiryMonth($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_expiry_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 card_expiry_year = 5;</code>
     * @return int
     */
    public function getCardExpiryYear()
    {
        return $this->card_expiry_year;
    }

    /**
     * Generated from protobuf field <code>int32 card_expiry_year = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCardExpiryYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->card_expiry_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 card_number = 6;</code>
     * @return int|string
     */
    public function getCardNumber()
    {
        return $this->card_number;
    }

    /**
     * Generated from protobuf field <code>uint64 card_number = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCardNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->card_number = $var;

        return $this;
    }

}

