<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/app.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\GetAppFilesResponse\Entry instead.
     * @deprecated
     */
    class GetAppFilesResponse_Entry {}
}
class_exists(GetAppFilesResponse\Entry::class);
@trigger_error('Toit\Api\GetAppFilesResponse_Entry is deprecated and will be removed in the next major release. Use Toit\Api\GetAppFilesResponse\Entry instead', E_USER_DEPRECATED);

