<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/app.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\GetAppFilesResponse\Directory instead.
     * @deprecated
     */
    class GetAppFilesResponse_Directory {}
}
class_exists(GetAppFilesResponse\Directory::class);
@trigger_error('Toit\Api\GetAppFilesResponse_Directory is deprecated and will be removed in the next major release. Use Toit\Api\GetAppFilesResponse\Directory instead', E_USER_DEPRECATED);

