<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\GetDevicePartitionsResponse\Partition instead.
     * @deprecated
     */
    class GetDevicePartitionsResponse_Partition {}
}
class_exists(GetDevicePartitionsResponse\Partition::class);
@trigger_error('Toit\Api\GetDevicePartitionsResponse_Partition is deprecated and will be removed in the next major release. Use Toit\Api\GetDevicePartitionsResponse\Partition instead', E_USER_DEPRECATED);

