<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/sdk.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.GetFirmwareElfResponse</code>
 */
class GetFirmwareElfResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes checksum = 1;</code>
     */
    protected $checksum = '';
    /**
     * Generated from protobuf field <code>bytes file = 2;</code>
     */
    protected $file = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $checksum
     *     @type string $file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes checksum = 1;</code>
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Generated from protobuf field <code>bytes checksum = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkString($var, False);
        $this->checksum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes file = 2;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Generated from protobuf field <code>bytes file = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->file = $var;

        return $this;
    }

}

