<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/organization.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ListAPIKeysResponse</code>
 */
class ListAPIKeysResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.APIKey api_key = 1;</code>
     */
    protected $api_key = null;
    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     */
    protected $offset = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\APIKey $api_key
     *     @type string $offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.APIKey api_key = 1;</code>
     * @return \Toit\Model\APIKey|null
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    public function hasApiKey()
    {
        return isset($this->api_key);
    }

    public function clearApiKey()
    {
        unset($this->api_key);
    }

    /**
     * Generated from protobuf field <code>.toit.model.APIKey api_key = 1;</code>
     * @param \Toit\Model\APIKey $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\APIKey::class);
        $this->api_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, False);
        $this->offset = $var;

        return $this;
    }

}

