<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/simulator.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ListSimulatorsResponse</code>
 */
class ListSimulatorsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes simulator_ids = 1;</code>
     */
    private $simulator_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $simulator_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Simulator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes simulator_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSimulatorIds()
    {
        return $this->simulator_ids;
    }

    /**
     * Generated from protobuf field <code>repeated bytes simulator_ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSimulatorIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->simulator_ids = $arr;

        return $this;
    }

}

