<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/user.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ListOrganizationsResponse</code>
 */
class ListOrganizationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .toit.model.Organization organizations = 1;</code>
     */
    private $organizations;
    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     */
    protected $offset = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\Organization[]|\Google\Protobuf\Internal\RepeatedField $organizations
     *     @type string $offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.Organization organizations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrganizations()
    {
        return $this->organizations;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.Organization organizations = 1;</code>
     * @param \Toit\Model\Organization[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrganizations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\Organization::class);
        $this->organizations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>bytes offset = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, False);
        $this->offset = $var;

        return $this;
    }

}

