<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/app.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ListAppsFilter</code>
 */
class ListAppsFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name_prefix = 1;</code>
     */
    protected $name_prefix = '';
    /**
     * Generated from protobuf field <code>bool latest = 2;</code>
     */
    protected $latest = false;
    /**
     * Generated from protobuf field <code>string namespace_prefix = 3;</code>
     */
    protected $namespace_prefix = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name_prefix
     *     @type bool $latest
     *     @type string $namespace_prefix
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\App::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name_prefix = 1;</code>
     * @return string
     */
    public function getNamePrefix()
    {
        return $this->name_prefix;
    }

    /**
     * Generated from protobuf field <code>string name_prefix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamePrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool latest = 2;</code>
     * @return bool
     */
    public function getLatest()
    {
        return $this->latest;
    }

    /**
     * Generated from protobuf field <code>bool latest = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setLatest($var)
    {
        GPBUtil::checkBool($var);
        $this->latest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace_prefix = 3;</code>
     * @return string
     */
    public function getNamespacePrefix()
    {
        return $this->namespace_prefix;
    }

    /**
     * Generated from protobuf field <code>string namespace_prefix = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespacePrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace_prefix = $var;

        return $this;
    }

}

