<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/sdk.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ListSDKsResponse</code>
 */
class ListSDKsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .toit.model.SDK sdks = 1;</code>
     */
    private $sdks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\SDK[]|\Google\Protobuf\Internal\RepeatedField $sdks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.SDK sdks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSdks()
    {
        return $this->sdks;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.model.SDK sdks = 1;</code>
     * @param \Toit\Model\SDK[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSdks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Model\SDK::class);
        $this->sdks = $arr;

        return $this;
    }

}

