<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/sdk.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.LookupSDKResponse</code>
 */
class LookupSDKResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string version = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>string created_by = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $created_by = '';
    /**
     * Generated from protobuf field <code>map<string, string> settings = 5 [deprecated = true];</code>
     * @deprecated
     */
    private $settings;
    /**
     * Generated from protobuf field <code>repeated string models = 6 [deprecated = true];</code>
     * @deprecated
     */
    private $models;
    /**
     * Generated from protobuf field <code>.toit.model.SDK sdk = 7;</code>
     */
    protected $sdk = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $version
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type string $created_by
     *     @type array|\Google\Protobuf\Internal\MapField $settings
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $models
     *     @type \Toit\Model\SDK $sdk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getName()
    {
        @trigger_error('name is deprecated.', E_USER_DEPRECATED);
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setName($var)
    {
        @trigger_error('name is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 2 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getVersion()
    {
        @trigger_error('version is deprecated.', E_USER_DEPRECATED);
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setVersion($var)
    {
        @trigger_error('version is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [deprecated = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     * @deprecated
     */
    public function getCreatedAt()
    {
        @trigger_error('created_at is deprecated.', E_USER_DEPRECATED);
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        @trigger_error('created_at is deprecated.', E_USER_DEPRECATED);
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        @trigger_error('created_at is deprecated.', E_USER_DEPRECATED);
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [deprecated = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     * @deprecated
     */
    public function setCreatedAt($var)
    {
        @trigger_error('created_at is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_by = 4 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getCreatedBy()
    {
        @trigger_error('created_by is deprecated.', E_USER_DEPRECATED);
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>string created_by = 4 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setCreatedBy($var)
    {
        @trigger_error('created_by is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> settings = 5 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\MapField
     * @deprecated
     */
    public function getSettings()
    {
        @trigger_error('settings is deprecated.', E_USER_DEPRECATED);
        return $this->settings;
    }

    /**
     * Generated from protobuf field <code>map<string, string> settings = 5 [deprecated = true];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     * @deprecated
     */
    public function setSettings($var)
    {
        @trigger_error('settings is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->settings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string models = 6 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     * @deprecated
     */
    public function getModels()
    {
        @trigger_error('models is deprecated.', E_USER_DEPRECATED);
        return $this->models;
    }

    /**
     * Generated from protobuf field <code>repeated string models = 6 [deprecated = true];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @deprecated
     */
    public function setModels($var)
    {
        @trigger_error('models is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->models = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.SDK sdk = 7;</code>
     * @return \Toit\Model\SDK|null
     */
    public function getSdk()
    {
        return $this->sdk;
    }

    public function hasSdk()
    {
        return isset($this->sdk);
    }

    public function clearSdk()
    {
        unset($this->sdk);
    }

    /**
     * Generated from protobuf field <code>.toit.model.SDK sdk = 7;</code>
     * @param \Toit\Model\SDK $var
     * @return $this
     */
    public function setSdk($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\SDK::class);
        $this->sdk = $var;

        return $this;
    }

}

