<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.LookupProgramsRequest</code>
 */
class LookupProgramsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     */
    protected $program_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $program_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     * @return string
     */
    public function getProgramName()
    {
        return $this->program_name;
    }

    /**
     * Generated from protobuf field <code>string program_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramName($var)
    {
        GPBUtil::checkString($var, True);
        $this->program_name = $var;

        return $this;
    }

}

