<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/organization.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.OrganizationChange</code>
 */
class OrganizationChange extends \Google\Protobuf\Internal\Message
{
    protected $change;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $city
     *     @type string $country
     *     @type string $phone_number
     *     @type string $cvr_number
     *           Not used
     *     @type string $name
     *     @type string $email
     *     @type string $vat_number
     *     @type string $vat_country_code
     *     @type string $address_line
     *     @type string $postal_code
     *     @type int $customer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->readOneof(1);
    }

    public function hasCity()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->readOneof(2);
    }

    public function hasCountry()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->readOneof(3);
    }

    public function hasPhoneNumber()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string cvr_number = 4;</code>
     * @return string
     */
    public function getCvrNumber()
    {
        return $this->readOneof(4);
    }

    public function hasCvrNumber()
    {
        return $this->hasOneof(4);
    }

    /**
     * Not used
     *
     * Generated from protobuf field <code>string cvr_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCvrNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->readOneof(5);
    }

    public function hasName()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->readOneof(6);
    }

    public function hasEmail()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vat_number = 7;</code>
     * @return string
     */
    public function getVatNumber()
    {
        return $this->readOneof(7);
    }

    public function hasVatNumber()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>string vat_number = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVatNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vat_country_code = 8;</code>
     * @return string
     */
    public function getVatCountryCode()
    {
        return $this->readOneof(8);
    }

    public function hasVatCountryCode()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>string vat_country_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVatCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address_line = 9;</code>
     * @return string
     */
    public function getAddressLine()
    {
        return $this->readOneof(9);
    }

    public function hasAddressLine()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>string address_line = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 10;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->readOneof(10);
    }

    public function hasPostalCode()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>string postal_code = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.Customer.Type customer = 11;</code>
     * @return int
     */
    public function getCustomer()
    {
        return $this->readOneof(11);
    }

    public function hasCustomer()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.toit.model.Customer.Type customer = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCustomer($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\Customer\Type::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getChange()
    {
        return $this->whichOneof("change");
    }

}

