<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ProgramSource\Files instead.
     * @deprecated
     */
    class ProgramSource_Files {}
}
class_exists(ProgramSource\Files::class);
@trigger_error('Toit\Api\ProgramSource_Files is deprecated and will be removed in the next major release. Use Toit\Api\ProgramSource\Files instead', E_USER_DEPRECATED);

