<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

if (false) {
    /**
     * This class is deprecated. Use Toit\Api\ProgramSource\Bundle instead.
     * @deprecated
     */
    class ProgramSource_Bundle {}
}
class_exists(ProgramSource\Bundle::class);
@trigger_error('Toit\Api\ProgramSource_Bundle is deprecated and will be removed in the next major release. Use Toit\Api\ProgramSource\Bundle instead', E_USER_DEPRECATED);

