<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/auth.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.RefreshRequest</code>
 */
class RefreshRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes refresh_token = 1;</code>
     */
    protected $refresh_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $refresh_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes refresh_token = 1;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refresh_token;
    }

    /**
     * Generated from protobuf field <code>bytes refresh_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->refresh_token = $var;

        return $this;
    }

}

