<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/sdk.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.RegisterSDKRequest</code>
 */
class RegisterSDKRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sdk = 1;</code>
     */
    protected $sdk = '';
    /**
     * Generated from protobuf field <code>bool keep_default = 2;</code>
     */
    protected $keep_default = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sdk
     *     @type bool $keep_default
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sdk = 1;</code>
     * @return string
     */
    public function getSdk()
    {
        return $this->sdk;
    }

    /**
     * Generated from protobuf field <code>bytes sdk = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSdk($var)
    {
        GPBUtil::checkString($var, False);
        $this->sdk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool keep_default = 2;</code>
     * @return bool
     */
    public function getKeepDefault()
    {
        return $this->keep_default;
    }

    /**
     * Generated from protobuf field <code>bool keep_default = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeepDefault($var)
    {
        GPBUtil::checkBool($var);
        $this->keep_default = $var;

        return $this;
    }

}

