<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/program.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.RunResponse</code>
 */
class RunResponse extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $out
     *     @type string $err
     *     @type int|string $exit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Program::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes out = 1;</code>
     * @return string
     */
    public function getOut()
    {
        return $this->readOneof(1);
    }

    public function hasOut()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>bytes out = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOut($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes err = 2;</code>
     * @return string
     */
    public function getErr()
    {
        return $this->readOneof(2);
    }

    public function hasErr()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bytes err = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 exit = 3;</code>
     * @return int|string
     */
    public function getExit()
    {
        return $this->readOneof(3);
    }

    public function hasExit()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 exit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExit($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

