<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/organization.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.UpdateOrganizationRequest</code>
 */
class UpdateOrganizationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .toit.api.OrganizationChange changes = 1;</code>
     */
    private $changes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Api\OrganizationChange[]|\Google\Protobuf\Internal\RepeatedField $changes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .toit.api.OrganizationChange changes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChanges()
    {
        return $this->changes;
    }

    /**
     * Generated from protobuf field <code>repeated .toit.api.OrganizationChange changes = 1;</code>
     * @param \Toit\Api\OrganizationChange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Toit\Api\OrganizationChange::class);
        $this->changes = $arr;

        return $this;
    }

}

