<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.WatchJobChangesRequest</code>
 */
class WatchJobChangesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional to listen on changes for a single device.
     *
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     */
    protected $device_id = '';
    /**
     * Optional to listen on changes for a single job.
     *
     * Generated from protobuf field <code>bytes job_id = 2;</code>
     */
    protected $job_id = '';
    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     */
    protected $watch_revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *           Optional to listen on changes for a single device.
     *     @type string $job_id
     *           Optional to listen on changes for a single job.
     *     @type int|string $watch_revision
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional to listen on changes for a single device.
     *
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Optional to listen on changes for a single device.
     *
     * Generated from protobuf field <code>bytes device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Optional to listen on changes for a single job.
     *
     * Generated from protobuf field <code>bytes job_id = 2;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Optional to listen on changes for a single job.
     *
     * Generated from protobuf field <code>bytes job_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, False);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     * @return int|string
     */
    public function getWatchRevision()
    {
        return $this->watch_revision;
    }

    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWatchRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->watch_revision = $var;

        return $this;
    }

}

