<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.WatchSessionChangesResponse</code>
 */
class WatchSessionChangesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceSessionChangeType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     */
    protected $watch_revision = 0;
    /**
     * Will be set if the type is DeviceSessionChangeTypeConnected
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_connected = 4;</code>
     */
    protected $last_connected = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $device_id
     *     @type int|string $watch_revision
     *     @type \Google\Protobuf\Timestamp $last_connected
     *           Will be set if the type is DeviceSessionChangeTypeConnected
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceSessionChangeType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceSessionChangeType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Toit\Model\DeviceSessionChangeType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>bytes device_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     * @return int|string
     */
    public function getWatchRevision()
    {
        return $this->watch_revision;
    }

    /**
     * Generated from protobuf field <code>int64 watch_revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWatchRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->watch_revision = $var;

        return $this;
    }

    /**
     * Will be set if the type is DeviceSessionChangeTypeConnected
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_connected = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastConnected()
    {
        return $this->last_connected;
    }

    public function hasLastConnected()
    {
        return isset($this->last_connected);
    }

    public function clearLastConnected()
    {
        unset($this->last_connected);
    }

    /**
     * Will be set if the type is DeviceSessionChangeTypeConnected
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_connected = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastConnected($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_connected = $var;

        return $this;
    }

}

