<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/api/device.proto

namespace Toit\Api\ConfigChange;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.api.ConfigChange.Broker</code>
 */
class Broker extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceBrokerSettings broker_settings = 1;</code>
     */
    protected $broker_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceBrokerSettings $broker_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Api\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceBrokerSettings broker_settings = 1;</code>
     * @return \Toit\Model\DeviceBrokerSettings|null
     */
    public function getBrokerSettings()
    {
        return $this->broker_settings;
    }

    public function hasBrokerSettings()
    {
        return isset($this->broker_settings);
    }

    public function clearBrokerSettings()
    {
        unset($this->broker_settings);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceBrokerSettings broker_settings = 1;</code>
     * @param \Toit\Model\DeviceBrokerSettings $var
     * @return $this
     */
    public function setBrokerSettings($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceBrokerSettings::class);
        $this->broker_settings = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Broker::class, \Toit\Api\ConfigChange_Broker::class);

