<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/pubsub/message.proto

namespace Toit\Model\Pubsub;

if (false) {
    /**
     * This class is deprecated. Use Toit\Model\Pubsub\Publisher\Device instead.
     * @deprecated
     */
    class Publisher_Device {}
}
class_exists(Publisher\Device::class);
@trigger_error('Toit\Model\Pubsub\Publisher_Device is deprecated and will be removed in the next major release. Use Toit\Model\Pubsub\Publisher\Device instead', E_USER_DEPRECATED);

