<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/pubsub/message.proto

namespace Toit\Model\Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.pubsub.Publisher</code>
 */
class Publisher extends \Google\Protobuf\Internal\Message
{
    protected $publisher;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\Pubsub\Publisher\Device $device
     *     @type \Toit\Model\Pubsub\Publisher\External $external
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Pubsub\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.pubsub.Publisher.Device device = 1;</code>
     * @return \Toit\Model\Pubsub\Publisher\Device|null
     */
    public function getDevice()
    {
        return $this->readOneof(1);
    }

    public function hasDevice()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.toit.model.pubsub.Publisher.Device device = 1;</code>
     * @param \Toit\Model\Pubsub\Publisher\Device $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\Pubsub\Publisher\Device::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.pubsub.Publisher.External external = 2;</code>
     * @return \Toit\Model\Pubsub\Publisher\External|null
     */
    public function getExternal()
    {
        return $this->readOneof(2);
    }

    public function hasExternal()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.toit.model.pubsub.Publisher.External external = 2;</code>
     * @param \Toit\Model\Pubsub\Publisher\External $var
     * @return $this
     */
    public function setExternal($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\Pubsub\Publisher\External::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPublisher()
    {
        return $this->whichOneof("publisher");
    }

}

