<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/pubsub/topic.proto

namespace Toit\Model\Pubsub;

use UnexpectedValueException;

/**
 * Protobuf type <code>toit.model.pubsub.TopicType</code>
 */
class TopicType
{
    /**
     * Generated from protobuf enum <code>TOPIC_TYPE_UNKNOWN = 0;</code>
     */
    const TOPIC_TYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>TOPIC_TYPE_CLOUD = 1;</code>
     */
    const TOPIC_TYPE_CLOUD = 1;
    /**
     * Generated from protobuf enum <code>TOPIC_TYPE_DEVICE = 2;</code>
     */
    const TOPIC_TYPE_DEVICE = 2;
    /**
     * Generated from protobuf enum <code>TOPIC_TYPE_DEVICE_MEMORY = 3;</code>
     */
    const TOPIC_TYPE_DEVICE_MEMORY = 3;

    private static $valueToName = [
        self::TOPIC_TYPE_UNKNOWN => 'TOPIC_TYPE_UNKNOWN',
        self::TOPIC_TYPE_CLOUD => 'TOPIC_TYPE_CLOUD',
        self::TOPIC_TYPE_DEVICE => 'TOPIC_TYPE_DEVICE',
        self::TOPIC_TYPE_DEVICE_MEMORY => 'TOPIC_TYPE_DEVICE_MEMORY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

