<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toit/model/device.proto

namespace Toit\Model\DeviceEvent\Info\Value;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>toit.model.DeviceEvent.Info.Value.Diff</code>
 */
class Diff extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive from = 1;</code>
     */
    protected $from = null;
    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive to = 2;</code>
     */
    protected $to = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Toit\Model\DeviceEvent\Info\Value\Primitive $from
     *     @type \Toit\Model\DeviceEvent\Info\Value\Primitive $to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Toit\Model\Device::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive from = 1;</code>
     * @return \Toit\Model\DeviceEvent\Info\Value\Primitive|null
     */
    public function getFrom()
    {
        return $this->from;
    }

    public function hasFrom()
    {
        return isset($this->from);
    }

    public function clearFrom()
    {
        unset($this->from);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive from = 1;</code>
     * @param \Toit\Model\DeviceEvent\Info\Value\Primitive $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceEvent\Info\Value\Primitive::class);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive to = 2;</code>
     * @return \Toit\Model\DeviceEvent\Info\Value\Primitive|null
     */
    public function getTo()
    {
        return $this->to;
    }

    public function hasTo()
    {
        return isset($this->to);
    }

    public function clearTo()
    {
        unset($this->to);
    }

    /**
     * Generated from protobuf field <code>.toit.model.DeviceEvent.Info.Value.Primitive to = 2;</code>
     * @param \Toit\Model\DeviceEvent\Info\Value\Primitive $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Toit\Model\DeviceEvent\Info\Value\Primitive::class);
        $this->to = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Diff::class, \Toit\Model\DeviceEvent_Info_Value_Diff::class);

